The Pyhton Programming language:Dates and time

In [1]:
import datetime as dt
import time as tm
import numpy as np
import math

In [3]:
tm.time()

1675079827.8722017

In [4]:
dtnow=dt.datetime.fromtimestamp(tm.time())
dtnow

datetime.datetime(2023, 1, 30, 17, 28, 40, 811442)

In [5]:
dtnow.year

2023

In [6]:
delta=dt.timedelta(days=100)
delta

datetime.timedelta(days=100)

In [7]:
today=dt.date.today()

In [8]:
today-delta

datetime.date(2022, 10, 22)

In [9]:
today>today-delta

True

lambda and list comprehensions

In [5]:
a= lambda a,b,c:a*c
a(1,2,3)

3

In [6]:
list1=[]
for a in range(1000):
    if a%2==0:
        list1.append(a)
list1

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

In [9]:
list2=[number for number in range(1000) if number%2==0]

In [10]:
list2

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

In [11]:
tup1=()

In [12]:
tup1

()

In [16]:
for i in range(100):
    tup1.append(i)
#will give an error because tuple is immutable

AttributeError: 'tuple' object has no attribute 'append'

In [2]:
p=np.array([1,2,3])
p

array([1, 2, 3])

In [3]:
p.ndim

1

In [22]:
p1=np.array([[1,2,3],[4,5,6]],np.int64)

In [23]:
p1

array([[1, 2, 3],
       [4, 5, 6]], dtype=int64)

In [24]:
p1.shape

(2, 3)

In [25]:
p1.ndim

2

In [26]:
p1.dtype

dtype('int64')

In [5]:
a=np.zeros((2,4))
a
b=np.ones((2,4))


In [6]:
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
c=np.empty((2,5))

In [9]:
c

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.29061074e-306, 1.89146896e-307],
       [7.56571288e-307, 3.11525958e-307, 1.24610723e-306,
        1.29061142e-306, 2.44524090e-154]])

In [11]:
d=np.arange(1,100)

In [12]:
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [15]:
even=np.arange(2,100,2)

In [16]:
even

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [17]:
h=np.linspace(0,2,15)

In [18]:
h

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        , 1.14285714, 1.28571429,
       1.42857143, 1.57142857, 1.71428571, 1.85714286, 2.        ])

In [22]:
f=np.array([33,45,66,-44,0,-2,-30])
f

array([ 33,  45,  66, -44,   0,  -2, -30])

In [23]:
c=(f-32)*(5/9)
c

array([  0.55555556,   7.22222222,  18.88888889, -42.22222222,
       -17.77777778, -18.88888889, -34.44444444])

In [24]:
c>-10

array([ True,  True,  True, False, False, False, False])

In [25]:
even=np.arange(100)

In [26]:
even.reshape(2,50)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98, 99]])

In [27]:
even%2==0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False])

In [37]:
for i in even.flat:
    if(i%2==0):
        even1=np.array([i])

In [38]:
even1

array([98])

In [64]:
matrix1=np.array([[7,8,9],[0,1,2],[1,2,3]])
matrix2=np.array([[5.4,4.6,6.7],[1.1,0.3,3.5],[0.6,0.78,6.9]])
matrix3=matrix1@matrix2

In [65]:
matrix3.shape

(3, 3)

In [66]:
matrix3

array([[ 52.  ,  41.62, 137.  ],
       [  2.3 ,   1.86,  17.3 ],
       [  9.4 ,   7.54,  34.4 ]])

In [67]:
matrix2.dtype

dtype('float64')

In [68]:
matrix3.dtype

dtype('float64')

In [69]:
matrix1.dtype

dtype('int32')

In [70]:
matrix3.size

9

In [71]:
matrix3.nbytes

72

In [73]:
matrix3.size*matrix3.itemsize

72

In [21]:
array1=np.arange(1,16)
array1=array1.reshape(3,5)

NameError: name 'np' is not defined

In [77]:
array1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [78]:
from PIL import image
from IPython.display import display
im=image.open('chris.tiff')
diplay(im)

ModuleNotFoundError: No module named 'PIL'

In [5]:
import PIL

In [20]:
from PIL import Image
from IPython.display import display
im= Image.open('IMG_0070.JPG',"rb")
diplay(im)

ValueError: bad mode 'rb'

Boolean indexing

In [3]:
a=np.array([[1,2,3],[4,5,6]])
print(a>5)

[[False False False]
 [False False  True]]


In [4]:
print(a[a>5])

[6]


slicing


In [12]:
array=np.array([[1,2,3],[4,5,6],[7,8,9]])
array[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [13]:

subarray=(array[0:2,1:3])
print(subarray[0,0])
subarray[0,0]=50
print(subarray[0,0])
print(a[0,1])

2
50
2


In [14]:
pokemon=np.genfromtxt('pokemon_data.csv',delimiter=",",skip_header=1)
pokemon

array([[  1.,  nan,  nan, ...,  45.,   1.,  nan],
       [  2.,  nan,  nan, ...,  60.,   1.,  nan],
       [  3.,  nan,  nan, ...,  80.,   1.,  nan],
       ...,
       [720.,  nan,  nan, ...,  70.,   6.,  nan],
       [720.,  nan,  nan, ...,  80.,   6.,  nan],
       [721.,  nan,  nan, ...,  70.,   6.,  nan]])

In [15]:
pokemon.shape

(800, 12)

In [16]:
print(pokemon[:,0])
print(pokemon[:,0:1])

[  1.   2.   3.   3.   4.   5.   6.   6.   6.   7.   8.   9.   9.  10.
  11.  12.  13.  14.  15.  15.  16.  17.  18.  18.  19.  20.  21.  22.
  23.  24.  25.  26.  27.  28.  29.  30.  31.  32.  33.  34.  35.  36.
  37.  38.  39.  40.  41.  42.  43.  44.  45.  46.  47.  48.  49.  50.
  51.  52.  53.  54.  55.  56.  57.  58.  59.  60.  61.  62.  63.  64.
  65.  65.  66.  67.  68.  69.  70.  71.  72.  73.  74.  75.  76.  77.
  78.  79.  80.  80.  81.  82.  83.  84.  85.  86.  87.  88.  89.  90.
  91.  92.  93.  94.  94.  95.  96.  97.  98.  99. 100. 101. 102. 103.
 104. 105. 106. 107. 108. 109. 110. 111. 112. 113. 114. 115. 115. 116.
 117. 118. 119. 120. 121. 122. 123. 124. 125. 126. 127. 127. 128. 129.
 130. 130. 131. 132. 133. 134. 135. 136. 137. 138. 139. 140. 141. 142.
 142. 143. 144. 145. 146. 147. 148. 149. 150. 150. 150. 151. 152. 153.
 154. 155. 156. 157. 158. 159. 160. 161. 162. 163. 164. 165. 166. 167.
 168. 169. 170. 171. 172. 173. 174. 175. 176. 177. 178. 179. 180. 181.
 181. 

In [20]:
pokemon[:,[0,2,4]]

array([[  1.,  nan,  45.],
       [  2.,  nan,  60.],
       [  3.,  nan,  80.],
       ...,
       [720.,  nan,  80.],
       [720.,  nan,  80.],
       [721.,  nan,  80.]])

In [21]:
pokemon[:,0:3]

array([[  1.,  nan,  nan],
       [  2.,  nan,  nan],
       [  3.,  nan,  nan],
       ...,
       [720.,  nan,  nan],
       [720.,  nan,  nan],
       [721.,  nan,  nan]])

In [23]:
pokemon[:,-3].mean()

68.2775

In [2]:
pokemon2=np.genfromtxt('pokemon_data.csv',dtype=None,delimiter=",",skip_header=1,names=('#','Name','Type 1','Type 2','HP','Attack','Defense','Sp. Atk','Sp. Def','Speed','Generation','Legendary'))

C:\Users\Admin\AppData\Local\Temp\ipykernel_10296\3380999073.py:1: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  pokemon2=np.genfromtxt('pokemon_data.csv',dtype=None,delimiter=",",skip_header=1,names=('#','Name','Type 1','Type 2','HP','Attack','Defense','Sp. Atk','Sp. Def','Speed','Generation','Legendary'))


In [3]:
pokemon2

array([(  1, b'Bulbasaur', b'Grass', b'Poison',  45,  49,  49,  65,  65,  45, 1, False),
       (  2, b'Ivysaur', b'Grass', b'Poison',  60,  62,  63,  80,  80,  60, 1, False),
       (  3, b'Venusaur', b'Grass', b'Poison',  80,  82,  83, 100, 100,  80, 1, False),
       (  3, b'VenusaurMega Venusaur', b'Grass', b'Poison',  80, 100, 123, 122, 120,  80, 1, False),
       (  4, b'Charmander', b'Fire', b'',  39,  52,  43,  60,  50,  65, 1, False),
       (  5, b'Charmeleon', b'Fire', b'',  58,  64,  58,  80,  65,  80, 1, False),
       (  6, b'Charizard', b'Fire', b'Flying',  78,  84,  78, 109,  85, 100, 1, False),
       (  6, b'CharizardMega Charizard X', b'Fire', b'Dragon',  78, 130, 111, 130,  85, 100, 1, False),
       (  6, b'CharizardMega Charizard Y', b'Fire', b'Flying',  78, 104,  78, 159, 115, 100, 1, False),
       (  7, b'Squirtle', b'Water', b'',  44,  48,  65,  50,  64,  43, 1, False),
       (  8, b'Wartortle', b'Water', b'',  59,  63,  80,  65,  80,  58, 1, False),
       (

In [4]:
pokemon2.shape

(800,)

In [5]:
pokemon2['Speed'][0:10]

array([ 45,  60,  80,  80,  65,  80, 100, 100, 100,  43])

In [6]:
pokemon2['Speed']=pokemon2['Speed']/10*4
pokemon2['Speed'][0:20]

array([18, 24, 32, 32, 26, 32, 40, 40, 40, 17, 23, 31, 31, 18, 12, 28, 20,
       14, 30, 58])

In [7]:
pokemon2.dtype

dtype([('f0', '<i4'), ('Name', 'S25'), ('Type_1', 'S8'), ('Type_2', 'S8'), ('HP', '<i4'), ('Attack', '<i4'), ('Defense', '<i4'), ('Sp_Atk', '<i4'), ('Sp_Def', '<i4'), ('Speed', '<i4'), ('Generation', '<i4'), ('Legendary', '?')])

In [8]:
pokemon.dtype

NameError: name 'pokemon' is not defined

In [9]:
len(pokemon2[pokemon2['Type_1']==b"Steel"])

27

In [13]:
print(pokemon2[pokemon2['Speed']>50]['Defense'].mean())

69.45


In [14]:
print(pokemon2[pokemon2['Speed']<50]['Defense'].mean())

73.96645161290323


In [16]:
pokemon2[pokemon2['Speed']>50]

array([( 15, b'BeedrillMega Beedrill', b'Bug', b'Poison',  65, 150,  40,  15,  80, 58, 1, False),
       ( 65, b'AlakazamMega Alakazam', b'Psychic', b'',  55,  50,  65, 175,  95, 60, 1, False),
       ( 94, b'GengarMega Gengar', b'Ghost', b'Poison',  60,  65,  80, 170,  95, 52, 1, False),
       (101, b'Electrode', b'Electric', b'',  60,  50,  70,  80,  80, 56, 1, False),
       (135, b'Jolteon', b'Electric', b'',  65,  65,  60, 110,  95, 52, 1, False),
       (142, b'Aerodactyl', b'Rock', b'Flying',  80, 105,  65,  60,  75, 52, 1, False),
       (142, b'AerodactylMega Aerodactyl', b'Rock', b'Flying',  80, 135,  85,  70,  95, 60, 1, False),
       (150, b'Mewtwo', b'Psychic', b'', 106, 110,  90, 154,  90, 52, 1,  True),
       (150, b'MewtwoMega Mewtwo X', b'Psychic', b'Fighting', 106, 190, 100, 154, 100, 52, 1,  True),
       (150, b'MewtwoMega Mewtwo Y', b'Psychic', b'', 106, 150,  70, 194, 120, 56, 1,  True),
       (169, b'Crobat', b'Poison', b'Flying',  85,  90,  80,  70,  80, 52,

In [27]:
import re

In [29]:
text="Good Morning "
if re.search("Morning",text):
    print("hhozefa")
else:
    print("Chod de")


hhozefa


In [34]:
text1="Hozefa Amar is a good boy.Musu amar is mother of Hozefa amar.Hozefa amar is the elder brother of timepass amar."
a=re.split("Hozefa",text1)

In [35]:
a

['',
 ' Amar is a good boy.Musu amar is mother of ',
 ' amar.',
 ' amar is the elder brother of timepass amar.']

In [36]:
b=re.findall("Hozefa",text1)

In [37]:
b

['Hozefa', 'Hozefa', 'Hozefa']

Pattern and character class

In [43]:
texte="abcaaabcaaacabcba"
re.findall("a",texte)

['a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a']

In [44]:
re.findall("[ab]",texte)

['a', 'b', 'a', 'a', 'a', 'b', 'a', 'a', 'a', 'a', 'b', 'b', 'a']

In [47]:
re.findall("[a][b-c]",texte)

['ab', 'ab', 'ac', 'ab']

In [48]:
re.findall("ab|ac",texte)

['ab', 'ab', 'ac', 'ab']

In [49]:
re.findall("[^a]",texte)

['b', 'c', 'b', 'c', 'c', 'b', 'c', 'b']

In [50]:
re.findall("^[^a]",texte)

[]

Quantifiers

In [53]:
re.findall("a{2,10}",texte)

['aaa', 'aaa']

In [54]:
re.findall("a{1,1}a{1,1}",texte)

['aa', 'aa']

In [55]:
re.findall("a{2, 2}",texte)

[]

In [56]:
re.findall("a{1,10}b{1,10}c{1,10}",texte)

['abc', 'aaabc', 'abc']

In [60]:
with open("hello.txt","r") as file:
    wikki=file.read()


In [61]:
wikki

'  CHAPTR = 11 \nKEEP OF EVIL HABITS\n\nDRINKING\nDrinking is a evil and a it is a pity thai is becoming more and more popular in the\nsociety. People think it is fasionable to drink and entertain guests as wellwith liquor.\nSome think any celebration or an occasion like marriage and social gathering is \nincomplete if drink are not served.Some people think it is a way for relaxation.This is \ndefinitely an improper way of relaxation.\n'

In [67]:
re.findall("[a-zA-z]{1,100}\[edit\]",wikki)

[]