In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3],dtype='int32')
a

AttributeError: module 'numpy' has no attribute 'array'

In [3]:
b=np.array([[1,2,3],[4,5,6]])
b

AttributeError: module 'numpy' has no attribute 'array'

In [4]:
a.shape

(3,)

In [5]:
b.shape

(2, 3)

In [6]:
a.itemsize

4

In [7]:
#totalsize
a.itemsize*a.size

12

In [8]:
a.nbytes

12

Accessing and changing value in column and row

In [9]:
hozefa=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
hozefa


array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [10]:
a[0,:]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [ ]:
a[1,5]


In [ ]:
a[:,2]

In [ ]:
a[0:2,0:5:2]

In [ ]:
a[1,3]

In [ ]:
a[0,5]

In [ ]:
#3d array
#1 element describe the number of list
#2 define the sublist of list
#3 define the number of element of that sub list
b=np.array([[[1,2],[2,3]],[[4,5],[5,6]]])
b

Initialzing array

In [ ]:
#All 0's matrix
np.zeros(5)

In [ ]:
np.zeros((2,3))

In [ ]:
#all 1's matrix
np.ones((2,3),dtype='int64')

In [ ]:
#full matrix of any number
np.full((3,3),99)

In [ ]:
np.full((3,),99)

In [ ]:
print(np.full_like(hozefa,18))
#but if we put shape instead of just of the arrray
print(hozefa.shape)
print(np.full_like(hozefa.shape,4))

In [ ]:
np.random.rand(4,2)


In [ ]:
np.random.randint(1,100,100)
#it will give an 1d array of size smae as last element any number between start(0) and 100(end) 

In [ ]:
#if we have to get random array with shape of different arraywee use
np.random.random_sample(hozefa.shape)

In [ ]:
np.random.randint(8,size=(3,3))

In [ ]:
np.identity(3)
#it requires only one parameter

In [ ]:
a=np.array([1,2,3])
r1=np.repeat(a,3)
print(r1)

In [ ]:
output=np.ones((5,5))
z=np.zeros((3,3))
z[1,1]=9
output[1:4,1:4]=z
output


##### Be Careful while copying

In [ ]:
a=np.array([1,2,3])
b=a
b[0]=100
print(b)
print(a)

In [ ]:
a=np.array([1,2,3])
b=a.copy()
b[0]=100
print(b,a)

#####Linear Alegbra

In [ ]:
a=np.ones((2,3))
b=np.full((3,2),2)
np.matmul(a,b)


In [ ]:
#Detrminant
arr=np.identity(3)
arr
np.linalg.det(arr)
#determinant formuale

####statistics

In [ ]:
stats=np.array([[1,2,3],[4,5,6]])
stats

In [ ]:
np.min(stats,axis=0)

In [ ]:
np.max(stats,axis=1)

In [ ]:
np.sum(stats)

In [ ]:
np.sum(stats,axis=0)

####reorganising array

In [ ]:
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after=before.reshape((4,2))
print(after)

In [11]:
#vertical stack
n1=np.array([1,2,3,4])
n2=np.array([5,6,7,8])
np.vstack((n1,n2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [19]:
ni=np.ones((2,))
n2=np.zeros((2,))
np.hstack((n1,n2))

array([1., 2., 3., 4., 0., 0.])

In [20]:
array1=np.genfromtxt('data.txt',delimiter=',')
array1

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [21]:
array1.shape

(3, 18)

In [22]:
array1.astype('int64')

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int64)

#####Boolean indexing and advanced indexing

In [23]:
array1>10
#it will return an boolean array of same size as that of the array with bool value

array([[False,  True,  True,  True,  True,  True, False, False,  True,
        False, False, False, False, False, False, False, False, False],
       [False,  True,  True,  True,  True,  True, False,  True, False,
        False, False, False, False, False, False, False,  True,  True],
       [False,  True,  True,  True,  True,  True, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [25]:
np.any(array1>50,axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [26]:
np.all(array1>50,axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [27]:
array1[array1>50]
#return the array of only that value which staisfies the condition

array([196.,  75., 766.,  75.,  55., 999.,  78.,  76.,  88.])

In [30]:
~((array1>50)  & (array1<100))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])