In [1]:
import numpy as p

In [2]:
a=p.array([1,2,3],p.int64)
b=p.array([1,2,3],dtype='int32')

In [3]:
b.dtype

dtype('int32')

In [4]:
b

array([1, 2, 3])

In [5]:
a



array([1, 2, 3], dtype=int64)

In [6]:
print(a)


[1 2 3]


In [7]:
dtype.a

NameError: name 'dtype' is not defined

In [8]:
a.dtype

dtype('int64')

In [9]:
a.shape


(3,)

In [11]:
b=p.array([[1,2,3],[4,5,6]],p.int32)

In [12]:
print(b)

[[1 2 3]
 [4 5 6]]


In [13]:
b.shape

(2, 3)

In [14]:
b.shape()

TypeError: 'tuple' object is not callable

In [15]:
b.shape

(2, 3)

In [16]:
b[0,1]

2

In [17]:
b[0,1]=99

In [18]:
print(b)

[[ 1 99  3]
 [ 4  5  6]]


In [19]:
print(b[1,2])

6


In [3]:
e=p.array([[1,2,3,4,5],[56,775,33,566,44]], p.int64)

In [4]:
print(e)


[[  1   2   3   4   5]
 [ 56 775  33 566  44]]


In [5]:
e.shape

(2, 5)

In [6]:
e.dtype

dtype('int64')

In [7]:
np=p.array([[1,2,3,4],[1,2,3,4],[1,2,33,4]], p.int64)
np1=p.array(((1,2,3,4),(1,2,3,4),(1,2,3,4)),p.int32)

In [ ]:
print(np)

In [ ]:
print(np1)

In [ ]:
list=eval(input("Enter list:"))
uni=[]
rep=[]
count=i=0
length=len(list)
while i<length:
    element=list[i]
    if element not in uni and element not in rep:
        i+=1
        for j in range(length):
            if(element==list[j]):
                count+=1
        else:
            print("element",element,"has frequency",count)
            if(count==1):
                uni.append(element)
            else:
                rep.append(element)
            count=0
    else:
        i+=1
print(uni)
print(rep)

In [ ]:
np.shape


In [8]:
np2=p.array({34,23,23})

In [9]:
np2

array({34, 23}, dtype=object)

In [10]:
np2.shape


()

In [11]:
np2.size

1

In [12]:
zero=p.zeros((2,4))

In [13]:
zero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
zero.size

8

In [15]:
ra=p.arange(15)

In [16]:
ra

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
rng=p.arange(15,15)

In [18]:
rng

array([], dtype=int32)

In [19]:
lspace=p.linspace(1,100,10)
#p.linspace(starting number,ending number,how many number we want)

In [20]:
lspace

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [21]:
np3=p.empty((8,6))
#it takes random number with 8d(row) and 6(column) element in 1 list
#8-no of row
#6-no of column
#8,6-nof of dimension ie 2 in this case

In [22]:
np3

array([[1.57314714e-311, 1.57314680e-311, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [25]:
np4=p.empty_like(lspace)

In [26]:
np4

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [27]:
np4[2]=88

In [28]:
np4

array([  1.,  12.,  88.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [29]:
lspace

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [30]:
np4=p.empty_like(np1)

In [31]:
np4

array([[257,   0,   0,   0],
       [  0,   0,   0,   0],
       [  0,   0,   0,   0]])

In [ ]:
np4[0:3]=88

In [ ]:
np4

In [ ]:
np4[1:1]=99

In [ ]:
np4

In [ ]:
np4[1,1]=99

In [ ]:
np4

In [ ]:
np4[0,3]=99

In [ ]:
np4

In [ ]:
np4[0:3]=100

In [ ]:
np4

In [ ]:
np4[0:3:1]=110
np4

In [ ]:
np4[0:3:2]=120
np4

In [ ]:
np4.id()

In [ ]:
np4.id

In [ ]:
a=10

In [ ]:
a.id()

In [ ]:
id(a)

In [ ]:
ide=p.identity(12)
ide

In [ ]:
ide.shape

In [ ]:
ide.size

In [34]:
arr=p.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [35]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [ ]:
arr=arr.reshape(3,33)

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [39]:
arr.raval()

AttributeError: 'numpy.ndarray' object has no attribute 'raval'

In [40]:
arr.ravel()


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [ ]:
arr

In [41]:
ax=[[1,2,3],[4,5,6],[7,8,9]]
axi=p.array(ax)
axi

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
axi.dtype

dtype('int32')

In [43]:
axi.sum(axis=0)

array([12, 15, 18])

In [44]:
axi.sum(axis=1)

array([ 6, 15, 24])

In [45]:
axi.sum(axis=2)

AxisError: axis 2 is out of bounds for array of dimension 2

In [46]:
axi.T
axi

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
print(axi)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [48]:
axi.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [49]:
axi=axi.T

In [50]:
axi

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [51]:
axi.flat

In [52]:
for i in axi.flat:
    print(i)

1
4
7
2
5
8
3
6
9


In [53]:
axi.ndim
#no of dimension

2

In [54]:
axi.nbytes
#no of bytes consumed by all the element

36

In [55]:
one=p.array([1,2,3,4,4])
one

array([1, 2, 3, 4, 4])

In [56]:
one.argmax()
#returns the index where there is maximum element

3

In [57]:
one.argmin()

0

In [58]:
one.argcount(4)

AttributeError: 'numpy.ndarray' object has no attribute 'argcount'

In [59]:
one.argsort()
# gives the list of index in which it arrage the index from min to max number in list

array([0, 1, 2, 3, 4], dtype=int64)

In [62]:
m1=[1,8,5,4,9]
m1.sort()

In [63]:
m1

[1, 4, 5, 8, 9]

In [64]:
m1.reverse()

In [65]:
m1

[9, 8, 5, 4, 1]

In [66]:
axi.argmax()

8

In [67]:
axi.argmin()

0

In [68]:
axi.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [69]:
axi.argmax(axis=1)

array([2, 2, 2], dtype=int64)

In [70]:
axi.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [71]:
axi.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)

In [72]:
axi.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [73]:
axi.ravel()

array([1, 4, 7, 2, 5, 8, 3, 6, 9])

In [74]:
axi.reshape(3,3)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
axi.argsort(axis=0)

In [ ]:
axi1=p.array([[1,45,6],[4,6,7],[7,84,3]])

In [ ]:
axi+axi1

In [ ]:
axi2=axi*axi1

In [ ]:
list=[34,35]
list1=[36,37]
list+list1

In [ ]:
axi2.argsort()
#by default wee can say it has axis=1

In [ ]:
axi2.argsort(axis=0)

In [ ]:
axi2.argsort(axis=1)

In [ ]:
axi2%axi

In [ ]:
p.sqrt(axi2)
#gives square root of the matrix

In [ ]:
axi.sum()

In [ ]:
axi.max()

In [ ]:
axi.min()


In [ ]:
axi.argmax()
#return the maximum value index

In [ ]:
ap=p.array([[1,6,3,4,6],[1,4,6,26,7],[2,4,6,71,8]])
ap

In [ ]:
p.sort(ap)

In [ ]:
p.reverse(ap)

In [ ]:
type(p.where(ap>20))

In [ ]:
p.count_nonzero(ap)

In [ ]:
ap.size